"""create external calendar accounts

Revision ID: b8dd279082ae
Revises: ed19e334a05d
Create Date: 2026-09-21 21:47:43.728737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8dd279082ae'
down_revision: Union[str, Sequence[str], None] = 'ed19e334a05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_calendar_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('google', name='calendar_provider'), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_external_calendar_user_provider')
    )
    op.create_index(op.f('ix_external_calendar_accounts_user_id'), 'external_calendar_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_calendar_accounts_user_id'), table_name='external_calendar_accounts')
    op.drop_table('external_calendar_accounts')
    # ### end Alembic commands ###
    # autogenerate は ENUM 型を削除しないため、明示的に drop する
    sa.Enum(name='calendar_provider').drop(op.get_bind(), checkfirst=False)
