"""add reauth required flag

Revision ID: cbde825a4534
Revises: b8dd279082ae
Create Date: 2026-09-21 22:04:03.111863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbde825a4534'
down_revision: Union[str, Sequence[str], None] = 'b8dd279082ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_calendar_accounts', sa.Column('reauth_required', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_calendar_accounts', 'reauth_required')
    # ### end Alembic commands ###
